#!/usr/bin/env python3
"""Generate lab artifacts from a topology.

Reads a topology TOML (see lab/topologies/) and writes, under artifacts/:

  domains/lab-<name>.xml     libvirt domain definitions
  lab-net-up.sh              bridges + nft setup (run as root)
  lab-net-down.sh            teardown (run as root)

and, under the data directory (default /home/lab), per node:

  domains/<name>/disk.qcow2  qcow2 overlay on the base image (persistent)
  domains/<name>/config.img  32 MiB FAT disk with config/juniper.conf (regenerated)
  domains/<name>/console.log serial console log (appended by libvirt)

The data directory's group must be the user QEMU runs as (see lab-host-setup.sh).
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tarfile
import tempfile
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DEFAULT_TOPOLOGY = REPO / "lab" / "topologies" / "day-01-routing.toml"
DEFAULT_DATA = Path(os.environ.get("LAB_DATA", "/home/lab"))
DOMAIN_PREFIX = "lab-"

IMAGE_GLOBS = {
    "vjunos-router": "vJunos-router-*.qcow2",
    "vjunos-switch": "vJunos-switch-*.qcow2",
}

# what the vendor images expect to see in SMBIOS (from vrnetlab's per-platform launch.py)
SMBIOS_PRODUCT = {
    "vjunos-router": "VM-VMX",
    "vjunos-switch": "VM-VEX",
}

# data-port count the base config advertises (vrnetlab's per-platform init.conf)
PORTS_DEFAULT = {
    "vjunos-router": 12,
    "vjunos-switch": 56,
}

DOMAIN_XML = """<domain type='kvm'>
  <name>{name}</name>
  <memory unit='MiB'>{memory}</memory>
  <currentMemory unit='MiB'>{memory}</currentMemory>
  <vcpu placement='static'>{vcpu}</vcpu>
  <cpu mode='host-passthrough' check='none'/>
  <os>
    <type arch='x86_64' machine='pc'>hvm</type>
  </os>
  <sysinfo type='smbios'>
    <system>
      <entry name='manufacturer'>Juniper</entry>
      <entry name='product'>{smbios_product}</entry>
      <entry name='family'>lab</entry>
    </system>
  </sysinfo>
  <cputune>
    <shares>{shares}</shares>
  </cputune>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='{disk}'/>
      <target dev='vda' bus='virtio'/>
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='raw'/>
      <source file='{config_img}'/>
      <target dev='sda' bus='usb'/>
    </disk>
    <controller type='usb' model='qemu-xhci'/>
{interfaces}
    <serial type='pty'>
      <log file='{console_log}' append='on'/>
      <target port='0'/>
    </serial>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
    <video>
      <model type='vga'/>
    </video>
  </devices>
</domain>
"""

IFACE_XML = """    <interface type='bridge'>
      <source bridge='{bridge}'/>
      <model type='virtio'/>
      <mac address='{mac}'/>
    </interface>"""

NET_UP = """#!/usr/bin/env bash
# generated by ops/lab-gen.py — regenerate, do not edit
set -euo pipefail

BRIDGES="{bridges}"
HOST_ADDR="{host_addr}"

for bridge in $BRIDGES; do
  ip link show "$bridge" >/dev/null 2>&1 || ip link add "$bridge" type bridge
  ip link set "$bridge" up
done
ip addr replace "$HOST_ADDR" dev {mgmt_bridge}

nft delete table inet lab_iso 2>/dev/null || true
nft add table inet lab_iso
nft add chain inet lab_iso input '{{ type filter hook input priority filter; policy accept; }}'
nft add rule inet lab_iso input iifname "{mgmt_bridge}" ip saddr {mgmt_subnet} ct state new drop
nft add chain inet lab_iso forward '{{ type filter hook forward priority filter; policy accept; }}'
for bridge in $BRIDGES; do
  nft add rule inet lab_iso forward iifname "$bridge" drop
done
nft add rule inet lab_iso forward oifname "{mgmt_bridge}" drop

echo "lab network up: $BRIDGES ($HOST_ADDR on {mgmt_bridge})"
"""

NET_DOWN = """#!/usr/bin/env bash
# generated by ops/lab-gen.py — regenerate, do not edit
set -euo pipefail

nft delete table inet lab_iso 2>/dev/null || true

for bridge in {link_bridges}; do
  ip link del "$bridge" 2>/dev/null || echo "note: $bridge still busy (running domain?)" >&2
done
ip addr del {host_addr} dev {mgmt_bridge} 2>/dev/null || true
ip link del {mgmt_bridge} 2>/dev/null || echo "note: {mgmt_bridge} still busy (running domain?)" >&2

echo "lab network down"
"""


def die(msg: str) -> None:
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def run(cmd: list[str]) -> None:
    subprocess.run(cmd, check=True)


def load_topology(path: Path) -> dict:
    if not path.is_file():
        die(f"no topology at {path}")
    with open(path, "rb") as fh:
        topo = tomllib.load(fh)
    nodes = topo.get("nodes") or []
    links = topo.get("links") or []
    if not nodes:
        die("topology has no [[nodes]]")
    names = [n["name"] for n in nodes]
    if len(set(names)) != len(names):
        die("duplicate node names")
    for node in nodes:
        for key in ("name", "kind", "mgmt_ip"):
            if key not in node:
                die(f"node {node.get('name', '?')} is missing '{key}'")
    for link in links:
        if len(link.get("nodes", [])) != 2:
            die(f"malformed link {link!r}: exactly two nodes required")
        for name in link["nodes"]:
            if name not in names:
                die(f"link references unknown node '{name}'")
    lab = topo.setdefault("lab", {})
    lab.setdefault("name", path.stem)
    lab.setdefault("mgmt_bridge", "lab-mgmt")
    lab.setdefault("mgmt_host_ip", "10.99.0.1")
    lab.setdefault("mgmt_prefix", 24)
    lab.setdefault("reserve_mb", 4096)
    topo["lab"] = lab
    topo["nodes"] = nodes
    topo["links"] = links
    return topo


def mem_available_mb() -> int | None:
    try:
        for line in Path("/proc/meminfo").read_text().splitlines():
            if line.startswith("MemAvailable:"):
                return int(line.split()[1]) // 1024
    except OSError:
        return None
    return None


def find_base_image(node: dict, data_dir: Path) -> Path:
    if "image" in node:
        image = Path(node["image"])
        if not image.is_absolute():
            image = data_dir / "images" / image
        if not image.is_file():
            die(f"image not found for node {node['name']}: {image}")
        return image
    pattern = IMAGE_GLOBS.get(node["kind"])
    if pattern is None:
        die(f"unknown kind '{node['kind']}' for node {node['name']}")
    matches = sorted((data_dir / "images").glob(pattern))
    if not matches:
        die(
            f"no base image for kind '{node['kind']}': expected {pattern} in {data_dir}/images "
            "(download it from Juniper's free lab download area)"
        )
    return matches[-1]


def node_interfaces(topo: dict) -> dict[str, list[str]]:
    """node name -> bridge list, management first, in data-port order."""
    lab = topo["lab"]
    interfaces: dict[str, list[str]] = {n["name"]: [lab["mgmt_bridge"]] for n in topo["nodes"]}
    for idx, link in enumerate(topo["links"], start=1):
        for name in link["nodes"]:
            interfaces[name].append(f"lab-l{idx}")
    return interfaces


def load_ssh_key_line(lab: dict) -> tuple[str, str]:
    """Return (config line, source) for the lab SSH public key, if any.

    Lookup order: $LAB_SSH_PUBKEY, [lab].ssh_pubkey_file, ~/.ssh/lab_ed25519.pub.
    """
    candidates: list[Path] = []
    if os.environ.get("LAB_SSH_PUBKEY"):
        candidates.append(Path(os.environ["LAB_SSH_PUBKEY"]))
    if lab.get("ssh_pubkey_file"):
        candidates.append(Path(lab["ssh_pubkey_file"]))
    candidates.append(Path.home() / ".ssh" / "lab_ed25519.pub")
    for path in candidates:
        if path.is_file():
            value = path.read_text().strip()
            if value:
                return f'ssh-ed25519 "{value}";', str(path)
    return "", ""


def render_init_conf(node: dict, lab: dict, ssh_key_line: str) -> str:
    template = (REPO / "lab" / "nodes" / "init.conf.tmpl").read_text()
    return (
        template.replace("{HOSTNAME}", node["name"])
        .replace("{MGMT_IP_IPV4}", node["mgmt_ip"])
        .replace("{MGMT_GW_IPV4}", lab["mgmt_host_ip"])
        .replace("{PORTS}", str(node.get("ports", PORTS_DEFAULT.get(node["kind"], 12))))
        .replace("{SSH_KEY_LINE}", ssh_key_line)
    )


def build_config_disk(node: dict, lab: dict, domain_dir: Path, ssh_key_line: str) -> None:
    staging = Path(tempfile.mkdtemp(prefix="lab-cfg-"))
    try:
        conf_dir = staging / "config"
        conf_dir.mkdir()
        conf = render_init_conf(node, lab, ssh_key_line)
        startup = node.get("startup_config")
        if startup:
            conf += "\n" + (REPO / startup).read_text()
        (conf_dir / "juniper.conf").write_text(conf)
        tarball = staging / "vmm-config.tgz"
        with tarfile.open(tarball, "w:gz") as tf:
            tf.add(conf_dir, arcname="config")
        image = domain_dir / "config.img"
        run(["qemu-img", "create", "-f", "raw", str(image), "32M"])
        run(["mkfs.vfat", "-n", "vmm-data", str(image)])
        run(["mcopy", "-o", "-i", str(image), str(tarball), "::"])
        os.chmod(image, 0o660)
    finally:
        shutil.rmtree(staging, ignore_errors=True)


def ensure_overlay(base: Path, domain_dir: Path, fresh: bool) -> Path:
    overlay = domain_dir / "disk.qcow2"
    if fresh and overlay.exists():
        overlay.unlink()
    if not overlay.exists():
        run(["qemu-img", "create", "-f", "qcow2", "-F", "qcow2", "-b", str(base), str(overlay)])
    os.chmod(overlay, 0o660)
    return overlay


def mac_for(ordinal: int, iface: int) -> str:
    return f"02:00:00:00:{ordinal:02x}:{iface:02x}"


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--topology", default=str(DEFAULT_TOPOLOGY))
    parser.add_argument("--data-dir", default=str(DEFAULT_DATA))
    parser.add_argument("--check", action="store_true", help="memory gate only")
    parser.add_argument("--net-only", action="store_true", help="write net scripts only")
    parser.add_argument("--fresh", action="store_true", help="recreate node overlays")
    args = parser.parse_args()

    # group-writable output: the data directory belongs to the QEMU runtime group
    os.umask(0o007)

    topology = Path(args.topology).resolve()
    data_dir = Path(args.data_dir)
    topo = load_topology(topology)
    lab = topo["lab"]

    need_mb = sum(int(n.get("memory_mb", 5120)) for n in topo["nodes"]) + int(lab["reserve_mb"])
    available = mem_available_mb()

    if args.check:
        if available is None:
            print("memory gate skipped: /proc/meminfo not readable here")
            return
        if available < need_mb:
            die(
                f"not enough memory: need {need_mb} MiB "
                f"({len(topo['nodes'])} nodes + {lab['reserve_mb']} MiB reserve), "
                f"{available} MiB available"
            )
        print(f"memory gate ok: {need_mb} MiB needed, {available} MiB available")
        return

    artifacts = REPO / "artifacts"
    (artifacts / "domains").mkdir(parents=True, exist_ok=True)

    if not args.net_only:
        ssh_key_line, ssh_key_source = load_ssh_key_line(lab)
        if ssh_key_line:
            print(f"admin ssh key: embedded from {ssh_key_source}")
        else:
            print("admin ssh key: none found (nodes will accept the lab password only)")
        interfaces = node_interfaces(topo)
        ordinals = {n["name"]: i for i, n in enumerate(topo["nodes"], start=1)}
        for node in topo["nodes"]:
            name = node["name"]
            memory = int(node.get("memory_mb", 5120))
            vcpu = int(node.get("vcpu", 4))
            domain_dir = data_dir / "domains" / name
            domain_dir.mkdir(parents=True, exist_ok=True)
            base = find_base_image(node, data_dir)
            disk = ensure_overlay(base, domain_dir, args.fresh)
            build_config_disk(node, lab, domain_dir, ssh_key_line)
            console_log = domain_dir / "console.log"
            if not console_log.exists():
                console_log.touch(mode=0o660)
            iface_xml = "\n".join(
                IFACE_XML.format(bridge=bridge, mac=mac_for(ordinals[name], idx))
                for idx, bridge in enumerate(interfaces[name])
            )
            xml = DOMAIN_XML.format(
                name=DOMAIN_PREFIX + name,
                memory=memory,
                vcpu=vcpu,
                shares=int(node.get("cpu_shares", 256)),
                smbios_product=node.get("smbios_product", SMBIOS_PRODUCT.get(node["kind"], "VM-VMX")),
                disk=disk,
                config_img=domain_dir / "config.img",
                console_log=domain_dir / "console.log",
                interfaces=iface_xml,
            )
            out = artifacts / "domains" / f"{DOMAIN_PREFIX}{name}.xml"
            out.write_text(xml)
            print(f"node {name}: {vcpu} vCPU / {memory} MiB / base {base.name}")

    link_bridges = [f"lab-l{i}" for i in range(1, len(topo["links"]) + 1)]
    bridges = [lab["mgmt_bridge"], *link_bridges]
    host_addr = f"{lab['mgmt_host_ip']}/{lab['mgmt_prefix']}"
    mgmt_subnet = f"{lab['mgmt_host_ip'].rsplit('.', 1)[0]}.0/{lab['mgmt_prefix']}"

    up = artifacts / "lab-net-up.sh"
    down = artifacts / "lab-net-down.sh"
    up.write_text(
        NET_UP.format(
            bridges=" ".join(bridges),
            host_addr=host_addr,
            mgmt_bridge=lab["mgmt_bridge"],
            mgmt_subnet=mgmt_subnet,
        )
    )
    down.write_text(
        NET_DOWN.format(
            link_bridges=" ".join(link_bridges),
            host_addr=host_addr,
            mgmt_bridge=lab["mgmt_bridge"],
        )
    )
    os.chmod(up, 0o755)
    os.chmod(down, 0o755)

    if not args.net_only:
        if available is not None:
            print(f"memory: {need_mb} MiB needed, {available} MiB available")
        print(f"topology: {lab['name']} — {len(topo['nodes'])} nodes, {len(topo['links'])} links")


if __name__ == "__main__":
    main()
